name: smart_player_kit
description: "Advanced Flutter media player — HLS, subtitles, reels, mini player, background playback & analytics."

version: 1.0.1
homepage: https://github.com/flutterbysunny/smart_player_kit
repository: https://github.com/flutterbysunny/smart_player_kit
issue_tracker: https://github.com/flutterbysunny/smart_player_kit/issues

# pub.dev topics — search mein dikhne ke liye (max 5)
topics:
  - video
  - audio
  - media-player
  - streaming
  - hls

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # ─── Video Player ───────────────────────────────────────────────────────────
  video_player: ^2.11.1
  just_audio: ^0.10.5
  audio_session: ^0.2.3
  shared_preferences: ^2.5.5
  dio: ^5.9.2
  http: ^1.6.0
  connectivity_plus: ^7.1.1
  wakelock_plus: ^1.6.1
  screen_brightness: ^2.1.8
  volume_controller: ^3.5.0
  flutter_cache_manager: ^3.4.1
  flutter_local_notifications: ^21.0.0

  # ─── Platform Interface ─────────────────────────────────────────────────────
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.smart_player_kit
        pluginClass: SmartPlayerKitPlugin
      ios:
        pluginClass: SmartPlayerKitPlugin

platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux: